# Generated by Django 4.1.3 on 2022-12-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('qr_code', models.ImageField(upload_to='qrcodes/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
